"""S13-T04: verify each benchmark row's closing file exists at the final path and carries key terms. Read-only."""
import json, re, sys
from pathlib import Path
E = Path("skills")  # run from the engine root
S = {  # short aliases -> path under skills/
 "brand": "strategy/brand-strategy-and-distinctive-assets/SKILL.md",
 "lsbr": "strategy/brand-strategy-and-distinctive-assets/references/long-short-balance-and-reach.md",
 "btrack": "strategy/brand-strategy-and-distinctive-assets/references/brand-tracking.md",
 "cep": "strategy/brand-strategy-and-distinctive-assets/references/cep-and-mental-availability.md",
 "daa": "strategy/brand-strategy-and-distinctive-assets/references/distinctive-asset-audit.md",
 "asb": "advertising/advertising-strategy-and-budget/SKILL.md",
 "oma": "advertising/advertising-strategy-and-budget/references/objectives-and-measurement-architecture.md",
 "dms": "pipeline/06-digital-marketing-strategy/SKILL.md",
 "li": "platforms/platform-linkedin/SKILL.md",
 "mp": "advertising/media-planning/SKILL.md",
 "mbp": "meta-analytics-ops/meta-budget-planner/SKILL.md",
 "tcb": "strategy/traction-channel-bullseye/SKILL.md",
 "sca": "strategy/strategy-channel-architecture/SKILL.md",
 "cbb": "advertising/creative-brief-and-big-idea/SKILL.md",
 "cep2": "advertising/creative-brief-and-big-idea/references/creative-effectiveness-and-pretesting.md",
 "stp": "strategy/marketing-foundations-stp-positioning/SKILL.md",
 "bvi": "pipeline/04-brand-voice-intake/SKILL.md",
 "sms": "pipeline/05-social-media-strategy/SKILL.md",
 "cp": "pipeline/10-content-pillars/SKILL.md",
 "seo": "seo-discovery/seo-geo-optimisation/SKILL.md",
 "blog": "content-writing/blog-writer/SKILL.md",
 "fb": "platforms/platform-facebook/SKILL.md",
 "mcr": "meta-analytics-ops/meta-content-repurposing/SKILL.md",
 "abcd": "advertising/ad-copy-and-hook-lab/references/abcd-video-craft-and-ai-volume.md",
 "svc": "strategy/strategy-video-content/SKILL.md",
 "aitp": "policies/policy-ai-content-ethics/references/ai-transparency-and-provenance.md",
 "pcp": "playbooks/playbook-content-production/SKILL.md",
 "inf": "pipeline/08-influencer-marketing-strategy/SKILL.md",
 "ss": "playbooks/playbook-social-selling/SKILL.md",
 "msl": "meta-analytics-ops/meta-social-listening/SKILL.md",
 "psa": "playbooks/playbook-paid-social-advertising/SKILL.md",
 "mtp": "meta-analytics-ops/measurement-tracking-plan/SKILL.md",
 "mtpdir": "meta-analytics-ops/measurement-tracking-plan/references",
 "attr": "advertising/advertising-attribution-and-measurement/SKILL.md",
 "geo": "advertising/advertising-attribution-and-measurement/references/geo-power-and-incrementality-hierarchy.md",
 "pel": "content-writing/prompt-engineering-library/SKILL.md",
 "cert": "playbooks/playbook-agency-operations/references/certification-and-competency-register.md",
 "bdc": "business-development/biz-dev-credentials/SKILL.md",
 "psearch": "advertising/paid-search-advertising/SKILL.md",
 "feeds": "advertising/paid-search-advertising/references/shopping-and-feeds.md",
 "vis": "advertising/programmatic-and-brand-safety/references/viewability-ivt-and-attention.md",
 "spo": "advertising/programmatic-and-brand-safety/references/buying-routes-and-supply-path.md",
 "bss": "advertising/programmatic-and-brand-safety/references/brand-safety-and-suitability.md",
 "ctv": "advertising/programmatic-and-brand-safety/references/ctv-dooh-and-audio.md",
 "eamm": "advertising/media-planning/references/east-african-media-mix.md",
 "pod": "strategy/strategy-video-content/references/podcast-and-audio-series.md",
 "elr": "meta-analytics-ops/meta-reporting/references/effectiveness-ladder-review.md",
 "tex": "meta-analytics-ops/meta-testing-framework/references/trustworthy-experiments-srm-power-holdouts.md",
 "trig": "advertising/ad-testing-and-scaling/references/test-rigour-srm-and-preregistration.md",
 "mmm": "advertising/marketing-mix-modelling/SKILL.md",
 "mr": "advertising/marketing-mix-modelling/references/meridian-and-robyn-choice.md",
 "cal": "advertising/marketing-mix-modelling/references/calibration-and-geo-experiments.md",
 "tri": "advertising/marketing-mix-modelling/references/triangulation-and-decision-governance.md",
 "roi": "meta-analytics-ops/meta-roi-framework/SKILL.md",
 "dre": "advertising/direct-response-economics/SKILL.md",
 "pcs": "playbooks/playbook-post-click-strategy/SKILL.md",
 "ewd": "playbooks/playbook-post-click-strategy/references/ecommerce-and-whatsapp-conversion-diagnosis.md",
 "a2s": "advertising/ad-to-site-journey-handoff/SKILL.md",
 "lpb": "advertising/ad-to-site-journey-handoff/references/landing-page-brief-template.md",
 "aigso": "ai-marketing/ai-generative-search-optimisation/SKILL.md",
 "wcp": "pipeline/12-website-content-plan/SKILL.md",
 "its": "pipeline/08-influencer-marketing-strategy/references/influencer-term-sheet-and-disclosure.md",
 "infdir": "pipeline/08-influencer-marketing-strategy",
 "ewom": "strategy/strategy-ewom-reviews/SKILL.md",
 "pcm": "playbooks/playbook-community-management/SKILL.md",
 "crp": "playbooks/playbook-crisis-communications/references/crisis-response-procedures.md",
 "crisis": "playbooks/playbook-crisis-communications/SKILL.md",
 "wapt": "platforms/platform-whatsapp/references/whatsapp-platform-pricing-and-templates.md",
 "wa": "platforms/platform-whatsapp/SKILL.md",
 "chat": "playbooks/playbook-chatbot-strategy/SKILL.md",
 "smp": "playbooks/playbook-social-media-policy/SKILL.md",
 "dlh": "pipeline/07-email-marketing-strategy/references/deliverability-and-lifecycle-holdouts.md",
 "ems": "pipeline/07-email-marketing-strategy/SKILL.md",
 "lpo": "business-development/biz-dev-lawful-prospecting-outreach/SKILL.md",
 "mssa": "meta-analytics-ops/meta-sales-marketing-alignment/SKILL.md",
 "msmf": "meta-analytics-ops/meta-social-metrics-framework/SKILL.md",
 "mtse": "meta-analytics-ops/meta-tools-stack-evaluation/SKILL.md",
 "aucm": "ai-marketing/ai-use-case-mapping/SKILL.md",
 "pma": "playbooks/playbook-marketing-automation/SKILL.md",
 "cgc": "playbooks/playbook-agency-operations/references/commercial-governance-and-contracts.md",
 "pol": "policies/policy-ai-content-ethics/SKILL.md",
 "ard": "ai-marketing/ai-readiness-diagnostic/SKILL.md",
 "pcai": "business-development/biz-dev-proposal/references/pitch-conduct-and-ai-clauses.md",
 "anti": "ai-marketing/anti-ai-slop/SKILL.md",
 "slop": "ai-marketing/ai-slop-audit/SKILL.md",
 "rem": "business-development/biz-dev-pricing-menu/references/remuneration-models-evidence.md",
 "tct": "training/training-client-team/SKILL.md",
 "pre": "playbooks/playbook-pr-publicity/references/pr-evaluation.md",
 "pkr": "playbooks/playbook-pr-publicity/references/publicity-kit-and-release-method.md",
 "pr": "playbooks/playbook-pr-publicity/SKILL.md",
 "rep": "playbooks/playbook-reputation-management/SKILL.md",
 "deep": "playbooks/playbook-crisis-communications/references/synthetic-media-and-deepfake-protocol.md",
 "cmm": "strategy/social-commerce-strategy/references/commerce-media-and-marketplaces.md",
 "scs": "strategy/social-commerce-strategy/SKILL.md",
 "shut": "playbooks/playbook-crisis-communications/references/internet-shutdown-contingency.md",
 "whsms": "playbooks/playbook-sms-whatsapp-marketing",
}
def txt(alias):
    p = E / S[alias]
    if p.is_dir():
        return "\n".join(f.read_text(encoding="utf-8") for f in sorted(p.rglob("*.md")) if f.name != "ALIAS.md"), p.exists()
    return (p.read_text(encoding="utf-8") if p.exists() else ""), p.exists()
def all_active():
    return "\n".join(f.read_text(encoding="utf-8") for f in sorted(E.rglob("*.md")) if f.name != "ALIAS.md")
# row -> list of (alias, [terms that must all appear, case-insensitive])
C = {
"SL01-C1": [("lsbr", ["60:40"]), ("asb", ["60:40"]), ("dms", ["60:40"])],
"SL01-C2": [("btrack", ["ladder"]), ("oma", ["WARC-EFFECTIVENESS-CODE-2020"])],
"SL01-C3": [("lsbr", ["95:5"]), ("li", ["95:5"]), ("mp", ["LINKEDIN-B2B-95-5"])],
"SL01-C4": [("asb", ["measurement"])],
"SL01-C5": [("mbp", ["benchmark"])],
"SL01-C6": [("dms", ["PREMIUM-ICC-2026"])],
"SL01-C7": [("tcb", ["bullseye"]), ("sca", ["role"])],
"SL02-C1": [("cep", ["EBI-CATEGORY-ENTRY-POINTS", "mental availability"])],
"SL02-C2": [("daa", ["EBI-DISTINCTIVE-ASSETS", "fame", "unique"])],
"SL02-C3": [("lsbr", ["penetration"])],
"SL02-C4": [("cep2", ["IPA-LONG-SHORT-2013", "emotional"])],
"SL02-C5": [("btrack", ["track"]), ("elr", ["brand"])],
"SL02-C6": [("stp", ["segment", "position"])],
"SL02-C7": [("bvi", ["voice"])],
"SL03-C1": [("sms", ["strategy"]), ("cp", ["pillar"])],
"SL03-C2": [("seo", ["GOOGLE-SPAM-POLICIES"]), ("blog", ["GOOGLE-SPAM-POLICIES"])],
"SL03-C3": [("fb", ["META-UNORIGINAL-CONTENT-2025"]), ("mcr", ["META-UNORIGINAL-CONTENT-2025"])],
"SL03-C4": [("abcd", ["ABCD"]), ("svc", ["YOUTUBE-ABCD"])],
"SL03-C5": [("aitp", ["C2PA", "AI info"])],
"SL03-C6": [("pcp", ["approval"])],
"SL04-C1": [("fb", ["Use when"]), ("li", ["Use when"])],
"SL04-C2": [("inf", ["Partnership Ads"])],
"SL04-C3": [("infdir", ["toggle"])],
"SL04-C4": [("ss", ["Thought Leader"])],
"SL04-C5": [("msl", ["escalat"])],
"SL05-C1": [("psa", ["Advantage+"])],
"SL05-C2": [("mtpdir", ["dedup", "event_id"])],
"SL05-C3": [("attr", ["holdout"]), ("geo", ["geo"])],
"SL05-C4": [("psa", ["META-SIEP-AD-LIBRARY-2026"])],
"SL05-C5": [("abcd", ["label"]), ("pel", ["label"])],
"SL05-C6": [("li", ["95:5"])],
"SL05-C7": [("cert", ["Meta"]), ("bdc", ["certif"])],
"SL06-C1": [("psearch", ["Performance Max"])],
"SL06-C2": [("feeds", ["MERCHANT-CENTER-PRODUCT-DATA", "GTIN"])],
"SL06-C3": [("mtpdir", ["enhanced conversions"])],
"SL06-C4": [("mtpdir", ["Consent Mode"])],
"SL06-C5": [("attr", ["Conversion Lift"])],
"SL06-C6": [("cert", ["GOOGLE-ADS-CERTIFICATIONS"])],
"SL07-C1": [("vis", ["viewab", "MRC"])],
"SL07-C2": [("vis", ["MRC-IVT-2020", "TAG-CERTIFIED-AGAINST-FRAUD"])],
"SL07-C3": [("spo", ["ads.txt", "sellers.json"])],
"SL07-C4": [("bss", ["WFA-GARM-DISCONTINUED-2024", "suitability"])],
"SL07-C5": [("vis", ["IAB-MRC-ATTENTION-2025"])],
"SL07-C6": [("ctv", ["CTV", "pod"])],
"SL07-C7": [("ctv", ["MRC-OOH-STANDARDS"]), ("eamm", ["outdoor"])],
"SL07-C8": [("ctv", ["audio"]), ("pod", ["IAB-TECHLAB-PODCAST-2-2"]), ("eamm", ["AFROBAROMETER-UG-RADIO-2026"])],
"SL08-C1": [("cep2", ["pre-test", "System1"])],
"SL08-C2": [("abcd", ["ABCD"])],
"SL08-C3": [("cep2", ["rational"])],
"SL08-C4": [("elr", ["ladder"])],
"SL08-C5": [("tex", ["SRM", "pre-regist"]), ("trig", ["SRM"])],
"SL08-C6": [("cep2", ["distinctive"]), ("daa", ["creative"])],
"SL08-C7": [("aitp", ["risk"])],
"SL08-C8": [("cbb", ["big idea"])],
"SL09-C1": [("mmm", ["Meridian", "Robyn"]), ("mr", ["Meridian", "Robyn"])],
"SL09-C2": [("cal", ["prior", "calibrat"])],
"SL09-C3": [("geo", ["power", "META-GEOLIFT"])],
"SL09-C4": [("geo", ["hierarchy"]), ("tri", ["IAB-INCREMENTAL-COMMERCE-MEDIA-2025"])],
"SL09-C5": [("mtpdir", ["Consent Mode", "enhanced conversions", "Conversions API"])],
"SL09-C6": [("tri", ["IAB-TECHLAB-CLEAN-ROOM", "clean room"])],
"SL09-C7": [("tri", ["triangulat"])],
"SL09-C8": [("roi", ["ROI"]), ("dre", ["LTV"])],
"SL10-C1": [("tex", ["SRM", "guardrail"]), ("pcs", ["trustworthy"])],
"SL10-C2": [("lpb", ["WEBDEV-CORE-WEB-VITALS", "INP"])],
"SL10-C3": [("ewd", ["GOOGLE-OPTIMIZE-SUNSET-2023"])],
"SL10-C4": [("mtpdir", ["server-side", "experiment"])],
"SL10-C5": [("pcs", ["WhatsApp"])],
"SL11-C1": [("aigso", ["AI Overviews"])],
"SL11-C2": [("aigso", ["llms.txt"])],
"SL11-C3": [("blog", ["expert"])],
"SL11-C4": [("seo", ["spam"])],
"SL11-C5": [("seo", ["GOOGLE-AI-FEATURES-2025", "GOOGLE-EXTENDED-2026"])],
"SL11-C6": [("elr", ["Search Console"])],
"SL11-C7": [("seo", ["Core Web Vitals"])],
"SL12-C1": [("infdir", ["UK-ASA-CMA-INFLUENCER-2026"])],
"SL12-C2": [("infdir", ["FTC-ENDORSEMENTS-REVIEWS-2026"])],
"SL12-C3": [("ewom", ["fake"])],
"SL12-C4": [("its", ["ICC-CODE-2024-TEXT", "virtual"])],
"SL12-C5": [("infdir", ["toggle"])],
"SL12-C6": [("inf", ["Partnership Ads"])],
"SL12-C7": [("infdir", ["KE-BCLB-GAMBLING-ADS-2025"])],
"SL13-C1": [("pcm", ["response"])],
"SL13-C2": [("crp", ["CIPR-CRISIS-SOCIAL-2024", "ramp-up"])],
"SL13-C3": [("wapt", ["24-hour", "service"]), ("chat", ["WHATSAPP-PRICING-2025"])],
"SL13-C4": [("smp", ["personal data"])],
"SL14-C1": [("dlh", ["GMAIL-SENDER-GUIDELINES", "YAHOO-SENDER-REQUIREMENTS", "DMARC", "one-click"])],
"SL14-C2": [("lpo", ["consent"]), ("ems", ["consent"])],
"SL14-C3": [("wapt", ["template", "opt-in"])],
"SL14-C4": [("mtpdir", ["first-party"])],
"SL14-C5": [("dlh", ["holdout"]), ("tex", ["holdout"])],
"SL14-C6": [("ems", ["win-back"]), ("mssa", ["scor"])],
"SL15-C1": [("mtpdir", ["BigQuery"])],
"SL15-C2": [("mtpdir", ["server-side", "GTM"])],
"SL15-C3": [("mtpdir", ["GOOGLE-CMP-TCF-2026"])],
"SL15-C4": [("mtpdir", ["UG-PDPO-OFFSHORE-2025"])],
"SL15-C5": [("tri", ["clean room"])],
"SL15-C6": [("msmf", ["KPI"]), ("mtpdir", ["UTM"])],
"SL16-C1": [("mtse", ["audit"])],
"SL16-C2": [("aucm", ["agent"]), ("pma", ["agent"])],
"SL16-C3": [("cgc", ["audit right", "CSFA"])],
"SL16-C4": [("mtpdir", ["server-side", "tag"])],
"SL16-C5": [("pma", ["human"])],
"SL17-C1": [("aitp", ["42001"])],
"SL17-C2": [("aitp", ["600-1"])],
"SL17-C3": [("aitp", ["IAB", "Disclosure Framework"])],
"SL17-C4": [("aitp", ["Art", "50"])],
"SL17-C5": [("aitp", ["AI info", "TikTok"])],
"SL17-C6": [("aitp", ["ICC"])],
"SL17-C7": [("pcai", ["clause"])],
"SL17-C8": [("anti", ["slop"]), ("slop", ["score"])],
"SL18-C1": [("rem", ["payment by results"])],
"SL18-C2": [("cgc", ["ANA"])],
"SL18-C3": [("pcai", ["Pitch Positive"])],
"SL18-C4": [("cgc", ["principal"]), ("mp", ["principal"])],
"SL18-C5": [("spo", ["transparency report"])],
"SL18-C6": [("elr", ["ladder"])],
"SL18-C7": [("bdc", ["credential"])],
"SL19-C1-C2": [("cert", ["Skillshop", "Meta"])],
"SL19-C3": [("cert", ["IPA"])],
"SL19-C4": [("cert", ["CIM"])],
"SL19-C5": [("tct", ["train"])],
"SL20-C1": [("pre", ["Barcelona", "AVE"])],
"SL20-C2": [("crisis", ["minute"])],
"SL20-C3": [("rep", ["monitor"])],
"SL20-C4": [("deep", ["deepfake"])],
"SL20-C5": [("pr", ["authentic"])],
"SL21-C1": [("cmm", ["IAB-MRC-RETAIL-MEDIA-2024"])],
"SL21-C2": [("cmm", ["incremental"])],
"SL21-C3": [("feeds", ["feed"])],
"SL21-C4": [("psa", ["Advantage+"]), ("psearch", ["Performance Max"])],
"SL21-C5": [("cmm", ["Jumia", "Jiji"])],
"SL21-C6": [("wapt", ["7 days", "click-to-WhatsApp"]), ("scs", ["WhatsApp"])],
"SL21-C7": [("scs", ["mobile money"])],
# East Africa
"EA Market size": [("eamm", ["DATAREPORTAL-TZ-2026", "DATAREPORTAL-RW-2026"])],
"EA Mobile-first": [("eamm", ["GSMA-SSA-MOBILE-ECONOMY"])],
"EA Mobile money": [("cmm", ["GSMA-MOBILE-MONEY-2025"])],
"EA M-Pesa": [("cmm", ["SAFARICOM-FY2026-MPESA"])],
"EA Payments law": [("cmm", ["UG-NPS-ACT-2020"])],
"EA Radio": [("eamm", ["AFROBAROMETER-UG-RADIO-2026"])],
"EA WhatsApp economics": [("wapt", ["WHATSAPP-RATE-CARD-EA", "Rest of Africa", "1 Oct"])],
"EA WhatsApp opt-in": [("wa", ["opt-in"])],
"EA Uganda DPPA": [("lpo", ["DPPA"])],
"EA Kenya DPA": [("lpo", ["KE-ODPC-DIRECT-MARKETING-2026"])],
"EA Tanzania PDPA": [("__all__", ["TZ-PDPA"])],
"EA Rwanda": [("__all__", ["RW-DPP-REGISTRATION-2026"])],
"EA Uganda advertising standards": [("__all__", ["UG-UCC-ADS-2019"])],
"EA Uganda online publishers": [("__all__", ["UG-UCC-ONLINE-PUBLISHERS"])],
"EA Kenya advertising code": [("__all__", ["KE-ASBK-CODE-2003"])],
"EA Kenya gambling": [("__all__", ["KE-BCLB-GAMBLING-ADS-2025"])],
"EA Kenya bulk SMS": [("__all__", ["KE-CA-POLITICAL-BULK-SMS-2017"])],
"EA Uganda cyber law": [("__all__", ["void"])],
"EA Facebook in Uganda": [("__all__", ["verify"])],
"EA Internet shutdowns": [("shut", ["shutdown"])],
"EA Uganda taxes": [("__all__", ["UG-DATA-EXCISE"])],
"EA Tanzania online content": [("__all__", ["TZ-ONLINE-CONTENT-2020"])],
"EA Marketplaces and streaming": [("cmm", ["Jumia", "Jiji", "Boomplay"])],
}
ALL = all_active()
out = {}
for row, checks in C.items():
    res = []
    for alias, terms in checks:
        if alias == "__all__":
            t, ok, path = ALL, True, "any active file"
        else:
            t, ok = txt(alias); path = S[alias]
        missing = [x for x in terms if x.lower() not in t.lower()]
        res.append({"path": path, "exists": ok, "missing": missing})
    out[row] = res
bad = {r: v for r, v in out.items() if any((not x["exists"]) or x["missing"] for x in v)}
print(json.dumps(bad, indent=1))
print("rows", len(C), "bad", len(bad))
Path(sys.argv[1]).write_text(json.dumps(out, indent=1), encoding="utf-8")
